"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_purple)\
$os\
$username\
[](fg:color_purple bg:color_bg1)\
$directory\
[](fg:color_bg1 bg:color_bg3)\
$git_branch\
$git_status\
[](fg:color_bg3 bg:color_bg1)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg1 bg:color_bg0)\
$time\
[ ](fg:color_bg0)\
$line_break$character"""

palette = 'kanagawa_wave'

[palettes.kanagawa_wave]
color_bg0 = '#1f1f28'     # Sumi Ink 1
color_bg1 = '#2a2a37'     # Sumi Ink 3
color_bg3 = '#363646'     # Sumi Ink 4
color_fg0 = '#dcd7ba'     # Fuji White
color_muted = '#727169'   # Fuji Gray
color_purple = '#957fb8'  # Oni Violet
color_aqua = '#6a9589'    # Wave Aqua 2
color_green = '#98bb6c'   # Spring Green
color_blue = '#7e9cd8'    # Wave Blue
color_orange = '#ffa066'  # Surimi Orange
color_red = '#c34043'     # Autumn Red
color_yellow = '#e6c384'  # Boat Yellow

[os]
disabled = false
style = "bg:color_purple fg:color_bg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_purple fg:color_bg0 bold"
style_root = "bg:color_purple fg:color_bg0 bold"
format = '[ $user ]($style)'

[directory]
style = "fg:color_blue bg:color_bg1 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol $branch ](fg:color_aqua bg:color_bg3 bold)]($style)'

[git_status]
style = "bg:color_bg3"
format = '[[($all_status$ahead_behind )](fg:color_green bg:color_bg3)]($style)'

[nodejs]
disabled = true

[c]
disabled = true

[cpp]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[php]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[haskell]
disabled = true

[python]
disabled = true

[docker_context]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $context) ](fg:color_blue bg:color_bg1)]($style)'

[conda]
style = "bg:color_bg1"
format = '[[ $symbol( $environment) ](fg:color_blue bg:color_bg1)]($style)'

[pixi]
style = "bg:color_bg1"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg1)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg0"
format = '[[  $time ](fg:color_muted bg:color_bg0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_purple)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
